### ISSUE TITLE
Suggested change to absolute paths + Missing files

### ISSUE THREAD

**Issue by sebastianpinedaar** [abacusai/ForecastPFN#1]
Hi! Congrats for the nice paper and thanks for open sourcing the code!  I have one question and one remark about the code:

*Question*:
I want to run the training example, but I got the following error: `No such file or directory: '[..]/ForecastPFN/academic_comparison/metalearned/project/storage/resources/tourism/cache.dill'`. However, I cannot find it in the repo. Is it possible to obtain these files somehow?

*Remark*:
I tried to rerun the inference example, however I faced some problems with some fixed paths, such as the one [HERE](https://github.com/abacusai/ForecastPFN/blob/5288b4339ba0f68656cc6d879d02f201a992e909/src/training/metalearned_validation.py#L2C74-L2C74). 

Thanks again!

Best,

Sebastian

**Comment by dooleys** [comment]
thank you for taking a look at our work! 

the error here comes from using an auxiliary dataset to validate performance during training. that dataset is large and was part of the Meta-N-BEATS project which we compare to in our paper. 
since this isn't necessary for the training pipeline, i have removed it from the repo in `src/training/train.py` file. it should now run without any problem.
